### ISSUE TITLE
Failed to parse URLCrazy output

### ISSUE THREAD

**Issue by bulldawgs34** [seanthegeek/domainaware#4]
I keep getting a " Failed to parse URLCrazy output" for every domain entered, yet DNStwist appears to work just fine. 

Additional info using pdb:
```
> /home/user/domainaware/domainaware.py(135)crazy_query()
-> output = check_output(dt_args, universal_newlines=True, stderr=PIPE)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 2959: invalid continuation byte
```

**Comment by seanthegeek** [comment]
Can you provide the input so I can reproduce this error?

**Comment by bulldawgs34** [comment]
mydomains.csv (similar to):
`vox.com`
+3 other domains in this file, none of which result in a parse error.

in the check_output function, dt_args = 
`['/file/path/to/URLCrazy/urlcrazy', '-f', 'csv', 'vox.com']`

This error also occurs on different attempts of check_output upon further inspection
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1699: invalid start byte`

Thanks for the quick response!

**Comment by seanthegeek** [comment]
Fixed!
