### ISSUE TITLE
Error if multiple domains are entered

### ISSUE THREAD

**Issue by nullenc0de** [seanthegeek/domainaware#7]
I edited the mydomains.txt file with two domains, each on a new line. I receive this message. If I enter only 1 domain, the tool works great!

Any idea why?

I did notice the readme says to edit the "mydomains.csv" but the github repo contains only mydomains.txt. So I made a mydomains.csv and it still fails.
```
root@kali:/opt/domainaware# cat mydomains.txt 
example.com
example.net
root@kali:/opt/domainaware# python2.7 domainaware --email
Traceback (most recent call last):
  File "domainaware", line 380, in <module>
    main()
  File "domainaware", line 356, in main
    known_domains.append(csv_row["Domain"])
KeyError: 'Domain'
```

**Comment by nullenc0de** [comment]
oops, user error!

**Comment by fenderstrato666** [comment]
What was the problem?

**Comment by seanthegeek** [comment]
@fenderstrato666 The input file needs a header called `Domain`, like this:

```csv
Domain
example.com
example.net
```

**Comment by fenderstrato666** [comment]
OK thx :-)
